### ISSUE TITLE
git recursive-blame as a plugin ehancement

### ISSUE THREAD

**Issue by VDuda** [scottgonzalez/recursive-blame#12]
Hello!

As an enhancement I was wondering whether there was any interest in allowing recursive-blame to be accessed as a git plugin. For example recursive-blame would be accessed doing the following: 
`git recursive-blame <args> `

Creating a git plugin is as simple as the following essentials:

1. Create a shell or bash script that does what you want to do
2. Name your shell script git-name where name is the command you want to run after typing `git`.
3. Put your script in /usr/local/bin or somewhere similar in your `$PATH`
4. Run your script using `git recursive-blame`

I would gladly implement this feature if there is interest.

**Comment by scottgonzalez** [comment]
That seems reasonable, and just requires adding another line in `package.json`. See #13 for my proposed implementation. I created the PR for your feedback.

**Comment by artburkart** [comment]
Such wow! So speed! @scottgonzalez :+1:

**Comment by scottgonzalez** [comment]
Published as v0.3.0. Thanks for the idea!
