### ISSUE TITLE
Recursive-blame based on initial line number

### ISSUE THREAD

**Issue by mhstnsc** [scottgonzalez/recursive-blame#14]
Hi,

I was thinking about the same type of blame but i tihnk is more useful if one can just give the current line and the recursive blame can track this line as it changed over time.

Of course each step of the recursive-blame must compute a new line number to track in the next blame

**Comment by scottgonzalez** [comment]
I don't see how that would be possible. Do you have an implementation in mind?

**Comment by mhstnsc** [comment]
Well. Conceptually, i did not check it in detail. I was planning to do it but i saw your work.

Input: desired line number
Output: previous line number

```
git blame 
extract the line
get the OLD-SHA from the blame
get the patch of OLD-SHA
based on patch determine line number in the old file (a process of reverse patch. "patch" can do a reverse operation)
IF line was added THEN
     stop
IF line was modifier THEN
     display the blamed info for the old line and leave user in some detached head so it can redo this process.

```

I wonder if i make any sense :)

It is mostly based on the idea that a patch is reversible

**Comment by scottgonzalez** [comment]
Ok, so you want this to track whatever line shows up in the standard diff output? That will give undesired results in many cases. I think this will be a fair amount of work for very little value. If someone else wants to implement this, I will review a PR, but I don't think I'd want to spend time on this implementation.

**Comment by mhstnsc** [comment]
Ok, then. Ill close it.
