### ISSUE TITLE
Use without pattern

### ISSUE THREAD

**Issue by Globegitter** [scottgonzalez/recursive-blame#8]
Is it possible to use this tool without any patterns? So if you just want to display the complete 'blame history' of a file?

**Comment by scottgonzalez** [comment]
No, and I'm not sure that a "blame history" without a pattern to recurse on would even make sense. Most of the blames would stay the same.

**Comment by Globegitter** [comment]
It just recurses over the complete commit history of the specified file.

**Comment by scottgonzalez** [comment]
I'm not sure how useful that would be with the dumb terminal output that this tool has. There's no paging, scrolling, etc, so it'd be pretty painful to work with.
